name: plearn
description: Plearn app
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

# ⬇️ dependencies는 딱 1개 블록만 존재!
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  table_calendar: ^3.1.0   # ✅ 여기 추가

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/          # (있다면 유지)
    # - assets/… (필요한 에셋들)
